version: '3.8'
services:

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    # env_file:
      # - .env

#   postgres:
#     image: postgres:13-alpine
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: CODE_TYPER_DB
#     ports:
#       - "5432:5432"

#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
#       PGADMIN_DEFAULT_PASSWORD: 'admin'
#     ports:
#       - '5050:80'
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin

# volumes:
#   pgadmin-data:
#   db-data: